timesheet/lib/timesheet_web/router.ex
defmodule TimesheetWeb.Router do
  use TimesheetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TimesheetWeb.Plugs.FetchCurrentUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/jobs", JobController
    get "/tasks/:id", TaskController, :show
    resources "/sessions", SessionController,
      only: [:new, :create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetWeb do
  #   pipe_through :api
  # end
end

timesheet/lib/timesheet_web/views/layout_view.ex
defmodule TimesheetWeb.LayoutView do
  use TimesheetWeb, :view
end

timesheet/lib/timesheet_web/templates/layout/app.html.eex
  
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Lens · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="col-4">
          <%= link "ACME Engineering", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
        </div>
        <div class="col-4">
          <ul class="navbar-nav mr-auto">
            <%= link "Home", to: Routes.page_path(@conn, :index), class: "nav-link" %>
            <%= link "Jobs", to: Routes.job_path(@conn, :index), class: "nav-link" %>  
            <%= if @current_user do %>
              <%= link "Your Tasks", to: Routes.user_path(@conn, :show, @current_user), class: "nav-link" %>
            <% end %>
              <%= link "Users", to: Routes.user_path(@conn, :index), class: "nav-link" %>  
          </ul>
        </div>
        <div class="col-4 text-light">
          <%= if @current_user do %>
            User: <%= link(@current_user.name, to: Routes.user_path(@conn, :show, @current_user)) %>
            (<%= link("Logout", to: Routes.session_path(@conn, :delete),
              method: :delete) %>)
          <% else %>
            <%= link("Login", to: Routes.session_path(@conn, :new)) %> |
            <%= link("Register", to: Routes.user_path(@conn, :new)) %>
          <% end %>
        </div>
      </nav>
      <div>
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end %>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>